fix: split insert, update, upsert
googleapis/nodejs-datastore pull request #693
Opened 2020-06-29 17:49 UTC by AVaksman

- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Towards #540

2020-07-29 22:54 UTC, BenWhitehead reviewed
In concept I think this is a great idea to clean up the confusion outlined in #540.

I however do not know typescript well enough to evaluate the actual code change, so I'll defer code approval to them.

2020-08-03 03:05 UTC, AVaksman commented
Currently functions `insert`, `update`, `upsert` and `save` are implemented in the base class `DatastoreRequest` as asynchronous functions. The functions are then inherited by `Datastore` and `Transaction` classes where `Datastore` functions are meant to be asynchronous, and execute an RPC each, but `Transaction` functions not. The `Transaction` functions are designed to only prep the `entity` and push to `modifiedEntities_` array while awaiting `Transaction.commit()`.
In this PR the aforementioned functions are moved from `DatastoreRequest` class to `Datastore and `Transaction` classes with the intended implementation in each of them.

2020-09-01 19:24 UTC, AVaksman commented
Gentle ping

2020-09-01 19:27 UTC, stephenplusplus requested changes

2020-09-01 20:06 UTC, AVaksman commented on src/index.ts
> +   * original
Addressed, thanks.

2020-09-01 20:06 UTC, AVaksman commented on src/index.ts
> +   * the
Addressed, thanks.

2020-09-01 20:06 UTC, AVaksman commented on src/index.ts
> +   * with
Addressed, thanks.

2020-09-01 20:06 UTC, AVaksman commented on src/index.ts
> +   * //-
Added, thanks.

2020-09-01 20:06 UTC, stephenplusplus approved these changes

2020-09-01 20:28 UTC, AVaksman commented
Thank you!

2020-09-01 20:28 UTC, merged