feat: introduce import/export + Index class
googleapis/nodejs-datastore pull request #734
Opened 2020-09-24 17:29 UTC by stephenplusplus

Fixes #685
Closes #687

This PR brings support for:

- New class! `datastore.index(indexId)`
- New methods! 
  - `datastore.export('my-bucket')`
  - `datastore.import('my-entitites-backup')`

#### To Dos
- [x] Implement new Index class
- [x] Add `datastore.export()`
- [x] Add `datastore.import()`
- [x] System tests
- [x] Unit tests
- [x] Samples
- [x] Sample tests
- [ ] JSDocs

2020-09-30 19:46 UTC, AVaksman requested changes

2020-09-30 19:46 UTC, AVaksman commented on src/index.ts
> +  extends google.datastore.admin.v1.IImportEntitiesRequest {
Should not expose `projectId` here as well. As it is overridden [later](https://github.com/stephenplusplus/nodejs-datastore/blob/4325cd2f89d37c10813bb89de92f6a93d7ae5f77/src/request.ts#L921)
```suggestion
  extends Omit<google.datastore.admin.v1.IImportEntitiesRequest, 'projectId'> {
```

2020-09-30 19:46 UTC, AVaksman commented on src/index.ts
> +  file?: string | {bucket: {name: string}; name: string};
Same concerns about `inputUrl` overriding `file` `kinds`/`namespaces` overriding `entityFilter`

2020-09-30 19:46 UTC, AVaksman commented on src/index-class.ts
> +  constructor(datastore: Datastore, name: string) {
Param name `name` or `id`?

2020-09-30 19:55 UTC, AVaksman commented
@stephenplusplus 
Should we also provide sample got `getIndexesStream`?
WDYT

2020-10-06 20:32 UTC, stephenplusplus commented
@AVaksman I've done these other items, just working on adding the `getIndexesStream()` method 👍🏻. Thanks for looking!

2020-10-08 04:10 UTC, AVaksman approved these changes

2020-10-08 15:40 UTC, merged